### ISSUE TITLE
Quiz Errror

### ISSUE THREAD

**Issue by Brenex** [spatel4140/bing-rewards#2]
![capture](https://user-images.githubusercontent.com/3178983/34941661-ab2439e2-f9c2-11e7-98d5-55dcf5f4c6d1.PNG)

**Comment by spatel4140** [comment]
Yes, this is one of the known issues mentioned in the readme that I've put aside for the time being. 

I'll let you know as soon as I have a fix.

**Comment by Brenex** [comment]
Just wanted to let you know that the quizes were working for a week but then stopped again. Here is the new error:
![image](https://user-images.githubusercontent.com/3178983/37099693-003c5096-21ef-11e8-9e85-cfa55e2fdb2c.png)

**Comment by spatel4140** [comment]
I got something similar about a week ago so I took a look at the page in Chrome and it looked like Microsoft was having temporary server issues for a few hours but it has been working ever since. 

Just wondering, does your dashboard have the new redesign since late January early February or does it still look the same as it always did? It can be viewed [here](https://account.microsoft.com/rewards/).

As for the issue with quizzes, I've added some sleep time after submitting an answer in the case that the issue is being caused by latency in displaying the overlay. The changes have not been committed yet as I'll have to observe its effectiveness over time.

**Comment by Brenex** [comment]
This is what it is showing when there are still quizes to complete. I am on the new dashboard.

![offers](https://user-images.githubusercontent.com/3178983/37487999-b2c433e8-2869-11e8-8933-d2e75f662a6e.PNG)

**here is the output for the command prompt:**
Enter   w for web search,
        m for mobile search,
        b for both searches,
        o for offers,
        a for all,
        r for remaining (default)
Input:  o

        You selected offers

> Starting offers

DevTools listening on ws://127.0.0.1:12522/devtools/browser/14766ae2-bedd-439f-8bb3-afedb41c22a7
       >> Logging in
           << Successfully logged in
       >> Trying Lara Croft reboot
           << Already checked
       >> Trying Warpspeed Quiz
              >>> Starting quiz
                     >>>> Multiple choice
                     >>>> Progress: [                              ] 0/5 (0%)
                  <<< Failed to complete quiz
           << Failed to complete Warpspeed Quiz
       >> Trying Et tu?
           << Already checked
       >> Trying Claim your points
           << Already checked
       >> Trying FINAL FANTASY XV WINDOWS ED
           << Already checked
       >> Trying Star Wars: The Last Jedi
           << Already checked
    < Failed to complete offers

**Comment by spatel4140** [comment]
I was able to determine the problem has something to do with actually starting the quiz. As a result, it may try to continue and even assume it's multiple choice when it's not. 

No fix yet but it's a start! Don't mean to leave you hanging.

**Comment by Brenex** [comment]
This has been working well since the last update. Closing for now
