### ISSUE TITLE
Nice Work!

### ISSUE THREAD

**Issue by ShoGinn** [spatel4140/bing-rewards#3]
Great work on the program, I was trying to figure out what your vision is for the software and why you are putting it up open source. I tested it out this morning and found it to be exactly necessary for what it is! I especially love the time.time random for searches.

I had been having trouble with word randomization and mobile and having it bring up alerts for mobile searches (huge PITA btw).

I modified the code a bit to make it work using the selenium grid and docker. 

Are you interested in adding that as a functionality? What I don't want to do is fork this and lose your programing acumen ;) 

I am a hack in comparison. 

One question I did have is, have you thought of using the argument for --incognito or --start-maximized?

I saw you specified the WxH but couldn't find any actual programatic reason to do that other than resize. 

Anyways just starting the dialog.

**Comment by spatel4140** [comment]
Hey ShoGinn, 

I really appreciate your kind words!

I guess I haven't given much thought about where this will go. It was mainly a way for me to learn (and earn points at the same time). Unfortunately, I've become really busy and haven't had the time I wished to keep putting out updates other than fixing bugs here and there.

The main reason for putting this up was to share with a friend. I thought it would be the most elegant way to provide patches as well as keep my code versioned and organized. And then to my surprise, others began cloning it. 

I specified the height and width of the window because I noticed a while back when I first created this, some web elements wouldn't show depending on the how big the screen was. So to fix this, I set a default size. Not sure how necessary it is now. 

Altogether, I would be honored to have you fork it! I may update my code with improvements every now and then but this should be it for the most part for now. Both selenium grid and docker sound like great additions! Who knows, I may just clone yours haha :)

**Comment by ShoGinn** [comment]
I was able to hack your code up to make it work for the grid. I ended up just adding to the config file (hub ip) and then modifying the run instead of -d to -g 

It should be easy to figure out.

My coding skills are slack at best.

One thing I noticed this morning also was that the quiz's aren't completing for some reason. need to debug that ;)

**Comment by spatel4140** [comment]
That sounds great! 

I don't think my coding skills are all that, I'm in the same boat as you just hacking away. 

As for the quizzes, yeah I noticed they only complete about half the time. I think it has something to do with the delay after an option is selected and the page reloads but not exactly sure. I haven't looked into it much yet.
